---
# Install KDE desktop env.
- name: Install KDE desktop(kde-plasma-desktop)
  ansible.builtin.apt:
    name: kde-plasma-desktop

- name: Install KDE desktop related packages
  ansible.builtin.apt:
    update_cache: yes 
    pkg:
    - libnotify-bin # To generate notification
    - ark # To get extract zip option in context menu

- name: Configure monitoring widgets
  copy:
    src: "{{ role_path }}/files/widgets/plasma-org.kde.plasma.desktop-appletsrc"
    dest: "/home/vagrant/.config/plasma-org.kde.plasma.desktop-appletsrc"
    owner: vagrant
    group: vagrant
    mode: '0755'
