---
# Install KDE desktop env.
- name: Install KDE desktop(kde-plasma-desktop)
  ansible.builtin.apt:
    name: kde-plasma-desktop=5.24.6

- name: Install KDE desktop related packages
  ansible.builtin.apt:
    update_cache: yes 
    pkg:
    - libnotify-bin # To generate notification
    - ark # To get extract zip option in context menu
