---

# JDK
jdk_version: "17.0.2"
jdk_download_url: https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_linux-x64_bin.tar.gz

# Maven
maven_version: "3.8.1"

# NodeJS
nodejs_version : "v16.16.0"
nodejs_download_url : https://nodejs.org/dist/{{nodejs_version}}/node-{{nodejs_version}}-linux-x64.tar.xz


# NodeJS
golang_version : "go.1.19"
golang_download_url : https://dl.google.com/go/{{golang_version}}.linux-amd64.tar.gz
