---

- name: Get status of Docker repository
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/docker.list
  register: docker_repo
  
# https://docs.docker.com/engine/install/ubuntu/  
- name: Add the Docker repository to the apt index
  ansible.builtin.shell: |
    # Add Docker’s official GPG key:
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    # Use the following command to set up the repository:
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  when:
    docker_repo.stat.exists == false
 
# Update repositories cache and install specified packages
- name: Install Docker
  ansible.builtin.apt:
    update_cache: yes 
    name: 
      - docker-ce={{ DOCKER_VERSION }}
      - docker-ce-cli={{ DOCKER_VERSION }}
      - containerd.io
      - docker-compose-plugin
  when:
    docker_repo.stat.exists == false
