---

- name: Get status of PGAdmin repository
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/pgadmin4.list
  register: pgadmin_repo
  
# https://www.pgadmin.org/download/pgadmin-4-apt/  
- name: Add the PGAdmin repository to the apt index
  ansible.builtin.shell: |
    # Install the public key for the repository (if not done previously):
    sudo curl https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo apt-key add
    # Create the repository configuration file:
    sudo sh -c 'echo "deb https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'
  when:
    pgadmin_repo.stat.exists == true
    
- name: Install PGAdmin Desktop only
  ansible.builtin.apt:
    name: pgadmin4-desktop
  when:
    pgadmin_repo.stat.exists == true
    
