---

- name: Get status of PostgreSQL repository
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/pgdg.list
  register: postgresql_repo
  
- name: Add the PostgreSQL repository to the apt index
  ansible.builtin.shell: |
    # Create the file repository configuration:
    sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
    # Import the repository signing key:
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  when:
    postgresql_repo.stat.exists == false
    
- name: Install PostgreSQL
  ansible.builtin.apt:
    name: postgresql
  when:
    postgresql_repo.stat.exists == false
    
