---

# Eclipse
eclipse_version_date: "2024-03"
eclipse_version_suffix: "R"
eclipse_version: "{{ eclipse_version_date }}-{{ eclipse_version_suffix }}"
eclipse_download_url: https://archive.eclipse.org/technology/epp/downloads/release/{{eclipse_version_date}}/{{eclipse_version_suffix}}/eclipse-jee-{{eclipse_version}}-linux-gtk-x86_64.tar.gz

# VS Code
vscode_version_identifier: "1655263335"
vscode_download_url: https://vscode.download.prss.microsoft.com/dbazure/download/stable/ddc367ed5c8936efe395cffeec279b04ffd7db78/code-stable-x64-1741787903.tar.gz #TODO:Need to find stable url for download #https://code.visualstudio.com/updates

# Postman
postman_version: "latest"
postman_download_url: https://dl.pstmn.io/download/latest/linux64

# Chrome
chrome_download_url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

# IntelliJ IDEA Community Edition
intellij_idea_ic_version: "2022.1.4"
intellij_idea_ic_build_version: "221.6008.13"
intellij_idea_ic_download_url: https://download-cdn.jetbrains.com/idea/ideaIC-2022.1.4.tar.gz

# Docker
DOCKER_VERSION: "5:20.10.16~3-0~ubuntu-jammy"

# Java Mission Control
jmc_version: "8.2.1_linux-x64"
jmc_download_url: https://download.java.net/java/GA/jmc8/03/binaries/jmc-{{jmc_version}}.tar.gz