---

- name: Check if Maven exists
  stat: path=/opt/development/apache-maven-{{maven_version}}
  register: maven_exists

- name: Download Maven
  get_url: 
    url: https://archive.apache.org/dist/maven/maven-3/{{maven_version}}/binaries/apache-maven-{{maven_version}}-bin.tar.gz
    dest: /tmp/apache-maven-{{maven_version}}-bin.tar.gz
  when:
    maven_exists.stat.exists == false

- name: Unpack Maven
  unarchive:
    src: /tmp/apache-maven-{{maven_version}}-bin.tar.gz
    dest: /opt/development
  when:
    maven_exists.stat.exists == false

- name: Link Maven to development bin
  ansible.builtin.file:
    src: /opt/development/apache-maven-{{maven_version}}/bin/
    dest: /opt/development/bin/mvn
    state: link
    owner: root
    group: root

- name: Add Maven to the shell environment
  copy:
    src: /lib/bashrc/mvn.bashrc
    dest: /home/vagrant/.bashrc.d/
    owner: vagrant
    group: vagrant
    mode: '0755'   

  
