---

- name: Ensure VS Code Repository key exists
  apt_key:
    url: "{{ microsoft_key_url }}"
    state: present

- name: Ensure APT repository file exists
  apt_repository:
    repo: "deb https://packages.microsoft.com/repos/vscode stable main"
    state: present
    filename: vscode

- name: Ensure VS Code is installed
  apt:
    name: code
    state: present
    update_cache: true

- name: get list of installed extensions
  command: 'sudo code --user-data-dir="~/.vscode-root" --list-extensions'
  register: installed_extensions

- name: install extensions
  command: sudo code --user-data-dir="~/.vscode-root" --install-extension redhat.vscode-yaml
  become: yes