---

- name: Ensure VS Code Repository key exists
  apt_key:
    url: "{{ microsoft_key_url }}"
    state: present

- name: Ensure APT repository file exists
  apt_repository:
    repo: "deb https://packages.microsoft.com/repos/vscode stable main"
    state: present
    filename: vscode

- name: Ensure VS Code is installed
  apt:
    name: code
    state: present
    update_cache: true

- name: install extensions
  become: true
  command: "sudo --user-data-dir=~/root code --install-extension {{ item }}"
  loop: "{{ vs_code_extensions }}"