---

- name: Include bashrc files
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    block: |
      # Source bashrc files
      if [ -d ${HOME}/.bashrc.d ]
      then
        for file in ~/.bashrc.d/*.bashrc
        do
          source "${file}"
        done
      fi
