---

# https://stackoverflow.com/questions/26740113/virtualbox-shared-folder-permissions
# Note: Requires virtualbox-guest-x11 to be installed. As vboxsf group will exist only post installation 
- name:  Add user to the vboxsf group within the guest VM.
  user:
    name: vagrant
    groups: vboxsf
    append: yes
    
- name: Copy files from profile.d to /etc/profile.d
  copy:
    src: "{{ role_path }}/files/profile.d/"
    dest: /etc/profile.d/
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Customize shell prompt
  copy:
    src: "{{ role_path }}/files/bashrc/shell-prompt.bashrc"
    dest: /home/vagrant/.bashrc.d/
    owner: vagrant
    group: vagrant
    mode: '0755'
    
- name: Include bashrc files
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    block: |
      # Source bashrc files
      if [ -d ${HOME}/.bashrc.d ]
      then
        for file in ~/.bashrc.d/*.bashrc
        do
          source "${file}"
        done
      fi

- name: Add inputrc file
  copy:
    src: "{{ role_path }}/files/inputrc/.inputrc"
    dest: /home/vagrant
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Add raven cow file
  copy:
    src: "{{ role_path }}/files/raven.cow"
    dest: /usr/share/cowsay/cows
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Add Raven startup script
  copy:
    src: "{{ role_path }}/files/.raven-startup.sh"
    dest: /opt/develop/packages/bin
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Add cron job to execute Raven startup script on boot
  ansible.builtin.cron:
    name: "Raven Startup"
    special_time: reboot
    job: "/opt/develop/packages/bin/.raven-startup.sh"
    user: vagrant

- name: Add Raven Audio Fixer script
  copy:
    src: "{{ role_path }}/files/.raven-audio-fixer.sh"
    dest: /opt/develop/packages/bin
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Add Raven Audio Fixer to the shell environment
  copy:
    src: "{{ role_path }}/files/bashrc/raven-audio-fixer.bashrc"
    dest: /home/vagrant/.bashrc.d/
    owner: vagrant
    group: vagrant
    mode: '0755'
