---

- name: Copy files from profile.d to /etc/profile.d
  copy:
    src: "{{ role_path }}/files/profile.d/"
    dest: /etc/profile.d/
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Include bashrc files
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    block: |
      # Source bashrc files
      if [ -d ${HOME}/.bashrc.d ]
      then
        for file in ~/.bashrc.d/*.bashrc
        do
          source "${file}"
        done
      fi

# https://github.com/yashendra-gupta/journal-devops/blob/master/linux/customize/customize-shell-prompt.md
- name: Customize shell prompt
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    block: |
      # Customize shell prompt
      export GIT_PS1_SHOWDIRTYSTATE=true
      export GIT_PS1_SHOWUNTRACKEDFILES=true
      export PS1='\[\033[1;32m\]\u@\h\[\033[00m\]:\[\033[1;34m\]\w\[\033[1;31m\]$(__git_ps1)\[\033[00m\]\$' 
      
- name: Add raven cow file
  copy:
    src: "{{ role_path }}/files/raven.cow"
    dest: /usr/share/cowsay/cows
    owner: vagrant
    group: vagrant
    mode: '0755'
