---

- name: Create directories, if it does not exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'
    recurse: yes
  loop:
    - /opt/development # development directory
    - /opt/development/bin # bin for development directory
    # "/opt/packages" <= For storing packages/software
    # "/opt/packages/extras" <= For storing unpacked additional versions of packages/software stored in /opt/packages or /opt/development
    # "/opt/packages/extras/raw" <= For storing original files tar, zips, deb, etc
    - /opt/packages/extras/raw
    - /opt/log # log directory under /opt
    - ~/.bashrc.d # bashrc directory
    - /home/vagrant/bin # bin directory under home directory of Vagrant user
    - /home/vagrant/workspace # workspace directory