---

- name: Create directories, if it does not exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'
    recurse: yes
  loop:
    - "{{ directories }}"