---

- name: Enable CPU usage widget and configure it
  ansible.builtin.blockinfile:
    path: ~/.config/plasma-org.kde.plasma.desktop-appletsrc
    block: |
      # CPU usage widget
      [Containments][2][Applets][37]
      immutability=1
      plugin=org.kde.plasma.systemmonitor
      
      [Containments][2][Applets][37][Configuration]
      PreloadWeight=100
      
      [Containments][2][Applets][37][Configuration][Appearance]
      chartFace=org.kde.ksysguard.piechart
      title=Individual Core Usage
      
      [Containments][2][Applets][37][Configuration][ConfigDialog]
      DialogHeight=540
      DialogWidth=720
      
      [Containments][2][Applets][37][Configuration][SensorColors]
      cpu/all/coreCount=61,233,142
      cpu/all/cpuCount=61,184,233
      cpu/all/name=67,61,233
      cpu/all/system=74,233,61
      cpu/all/usage=233,0,0
      cpu/all/user=233,61,95
      cpu/all/wait=227,233,61
      cpu/cpu0/frequency=206,233,61
      cpu/cpu0/name=233,61,61
      cpu/cpu0/system=61,233,221
      cpu/cpu0/temperature=61,233,178
      cpu/cpu0/usage=61,174,233
      cpu/cpu0/user=61,233,127
      cpu/cpu0/wait=233,77,61
      cpu/cpu1/frequency=61,189,233
      cpu/cpu1/name=123,61,233
      cpu/cpu1/system=233,131,61
      cpu/cpu1/temperature=233,101,61
      cpu/cpu1/usage=233,120,61
      cpu/cpu1/user=165,233,61
      cpu/cpu1/wait=219,233,61
      cpu/loadaverages/loadaverage1=233,61,78
      cpu/loadaverages/loadaverage15=61,130,233
      cpu/loadaverages/loadaverage5=233,61,193
      
      [Containments][2][Applets][37][Configuration][Sensors]
      highPrioritySensorIds=["cpu/all/name","cpu/all/cpuCount","cpu/all/coreCount","cpu/all/usage","cpu/all/system","cpu/all/user","cpu/all/wait","cpu/cpu0/name","cpu/cpu0/usage","cpu/cpu0/system","cpu/cpu0/user","cpu/cpu0/wait","cpu/cpu0/frequency","cpu/cpu0/temperature","cpu/cpu1/name","cpu/cpu1/usage","cpu/cpu1/system","cpu/cpu1/user","cpu/cpu1/wait","cpu/cpu1/frequency","cpu/cpu1/temperature","cpu/loadaverages/loadaverage15","cpu/loadaverages/loadaverage5","cpu/loadaverages/loadaverage1"]
      totalSensors=["cpu/all/usage"]

- name: Enable memory usage widget and configure it
  ansible.builtin.blockinfile:
    path: ~/.config/plasma-org.kde.plasma.desktop-appletsrc
    block: |
      # Memory usage widget
      [Containments][2][Applets][40]
      immutability=1
      plugin=org.kde.plasma.systemmonitor
      
      [Containments][2][Applets][40][Configuration]
      PreloadWeight=100
      
      [Containments][2][Applets][40][Configuration][Appearance]
      chartFace=org.kde.ksysguard.piechart
      title=Memory Usage
      
      [Containments][2][Applets][40][Configuration][ConfigDialog]
      DialogHeight=540
      DialogWidth=720
      
      [Containments][2][Applets][40][Configuration][SensorColors]
      memory/physical/application=255,255,127
      memory/physical/applicationPercent=61,233,230
      memory/physical/buffer=233,155,61
      memory/physical/cache=170,255,255
      memory/physical/free=40,156,106
      memory/physical/total=85,170,255
      memory/physical/used=233,69,69
      memory/swap/free=170,0,255
      memory/swap/total=85,0,127
      memory/swap/used=145,0,217
      
      [Containments][2][Applets][40][Configuration][Sensors]
      highPrioritySensorIds=["memory/physical/total","memory/physical/used","memory/physical/free","memory/physical/cache","memory/physical/buffer","memory/physical/application","memory/swap/total","memory/swap/used","memory/swap/free"]
      lowPrioritySensorIds=[]
      totalSensors=["memory/physical/usedPercent"]

- name: Enable Disk usage widget and configure it
  ansible.builtin.blockinfile:
    path: ~/.config/plasma-org.kde.plasma.desktop-appletsrc
    block: |
      # Disk usage widget
      [Containments][2][Applets][43]
      immutability=1
      plugin=org.kde.plasma.systemmonitor
      
      [Containments][2][Applets][43][Configuration]
      PreloadWeight=85
      
      [Containments][2][Applets][43][Configuration][Appearance]
      chartFace=org.kde.ksysguard.linechart
      title=Hard Disk Activity
      
      [Containments][2][Applets][43][Configuration][ConfigDialog]
      DialogHeight=540
      DialogWidth=720
      
      [Containments][2][Applets][43][Configuration][SensorColors]
      disk/all/free=61,199,233
      disk/all/read=233,120,61
      disk/all/total=92,233,61
      disk/all/used=252,0,4
      disk/all/write=61,174,233
      os/plasma/kfVersion=233,61,176
      
      [Containments][2][Applets][43][Configuration][Sensors]
      highPrioritySensorIds=["disk/all/total","disk/all/used","disk/all/free","disk/all/read","disk/all/write"]
      
- name: Enable Network usage widget and configure it
  ansible.builtin.blockinfile:
    path: ~/.config/plasma-org.kde.plasma.desktop-appletsrc
    block: |
      # Network usage widget
      [Containments][2][Applets][41]
      immutability=1
      plugin=org.kde.plasma.systemmonitor
      
      [Containments][2][Applets][41][Configuration]
      PreloadWeight=100
      
      [Containments][2][Applets][41][Configuration][Appearance]
      chartFace=org.kde.ksysguard.linechart
      title=Network speed
      
      [Containments][2][Applets][41][Configuration][ConfigDialog]
      DialogHeight=540
      DialogWidth=720
      
      [Containments][2][Applets][41][Configuration][SensorColors]
      network/all/download=61,174,233
      network/all/totalDownload=61,123,233
      network/all/totalUpload=104,61,233
      network/all/upload=233,120,61
      
      [Containments][2][Applets][41][Configuration][Sensors]
      highPrioritySensorIds=["network/all/download","network/all/upload","network/all/totalDownload","network/all/totalUpload"]
      
