---

- name: Copy raven-update shell script to bin
  copy:
    src: "{{ role_path }}/files/raven-update"
    dest: /opt/development/
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Add Raven update to the shell environment
  copy:
    src: "{{ role_path }}/files/raven-update/raven-update.bashrc"
    dest: /home/vagrant/.bashrc.d/
    owner: vagrant
    group: vagrant
    mode: '0755'  
