---

- name: Copy raven-update executables
  copy:
    src: "{{ role_path }}/files/raven-update"
    dest: /opt/development/
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Link Raven update to development bin
  ansible.builtin.file:
    src: /opt/development/raven-update
    dest: /opt/development/bin/raven-update
    state: link
    owner: root
    group: root
    
- name: Add Raven update to the shell environment
  copy:
    src: "{{ role_path }}/files/raven-update/raven-update.bashrc"
    dest: /home/vagrant/.bashrc.d/
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Create cron job to check for updates
  ansible.builtin.shell: |
    cron_update="* * * * * /home/vagrant/test-update/update.sh"
    crontab -l > crontab_tmp
    echo "$cron_update" >> crontab_tmp
    crontab crontab_tmp
    rm crontab_tmp
      
